In [ ]:
Iterating through Numpy:

In [1]:
import numpy as np

In [4]:
a = np.array([['hariram','suresh','shyam','ganga','rahul'],
             [40,50,60,70,80],
             [90,80,70,60,50]])

In [ ]:
Each iteration will be over the rows of the array.

In [5]:
for i in a:
    print('i=', i)

i= ['hariram' 'suresh' 'shyam' 'ganga' 'rahul']
i= ['40' '50' '60' '70' '80']
i= ['90' '80' '70' '60' '50']


In [ ]:
flattening a multi dimensional array....!

In [6]:
for x in a.flatten():     #Row Based splitting iterarion!
    print(x)

hariram
suresh
shyam
ganga
rahul
40
50
60
70
80
90
80
70
60
50


In [ ]:
Column based splitting iteration!

In [8]:
for y in a.flatten(order = 'F'): #Forton based iteration   ====>Column based iteration
    print(y)

hariram
40
90
suresh
50
80
shyam
60
70
ganga
70
60
rahul
80
50


In [ ]:
understanding 'nditer' *****

In [11]:
x = np.arange(12).reshape(3,4)

x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
x = np.arange(100).reshape(10,10)

x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
x = np.arange(36).reshape(6,6)

x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
by default flatten or nditer you are using default nature is row based splitting of the data ****

In [14]:
for i in np.nditer(x):  #Row based splitting
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


In [15]:
for i in np.nditer(x, order = 'F'):  #Row based splitting
    print(i)

0
6
12
18
24
30
1
7
13
19
25
31
2
8
14
20
26
32
3
9
15
21
27
33
4
10
16
22
28
34
5
11
17
23
29
35


In [ ]:
IQ: flatten vs nditer   ----->which one to choose?
    we have to go for nditer ----->***

In [ ]:
understanding the concept of deep copying and shallow copying:

In [ ]:
copy and view ***

In [ ]:
copy =>the entire data is copied!
View =>not actual copying of the data!

1mb of le =>copy=>copy
100gb of file =>view=>copy