In [1]:
import numpy as np

In [ ]:
#Arithmetic Operation in Numpy

In [2]:
a = np.array([10,10,10])

In [3]:
b = np.array([5,5,5])

In [4]:
a+b

array([15, 15, 15])

In [5]:
a*b

array([50, 50, 50])

In [6]:
a/b

array([2., 2., 2.])

In [7]:
a%b

array([0, 0, 0], dtype=int32)

In [8]:
(a*b)*2

array([100, 100, 100])

In [9]:
a/b #Modulus -->Remainder (IQ:-Difference between Modulus and divisor Operator)


array([2., 2., 2.])

In [10]:
a>35

array([False, False, False])

In [11]:
a<35

array([ True,  True,  True])

In [13]:
a**2 #-->Power operation

array([100, 100, 100], dtype=int32)

In [ ]:
Modifying and existing array rather than the creating new one

In [ ]:
#Req :Modify a value to 30

In [15]:
a*=30
a

array([9000, 9000, 9000])

In [16]:
a*=50
a

array([450000, 450000, 450000])

In [17]:
a*=1
a

array([450000, 450000, 450000])

In [18]:
b+=a
b

array([450005, 450005, 450005])

In [22]:
ages = np.array([12,32,45,67,85,33,56])

In [ ]:
REQ:find the sum of the entire array

In [23]:
ages.sum()

330

In [24]:
ages.max()

85

In [25]:
ages.min()

12

In [26]:
numbers = np.arange(12).reshape(3,4)

In [27]:
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
numbers = np.arange(96).reshape(8,12)


In [31]:
numbers

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
       [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])

In [33]:
numbers.shape

(8, 12)

In [ ]:
#In @DIM array ->axis 0 represents -->Column
axis 1 represents ---->Row

In [34]:
numbers.sum(axis=0) #Find the sum of each columns axis = 0

array([336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424])

In [36]:
numbers.sum(axis=1) #Find the sum of each row axis = 1

array([  66,  210,  354,  498,  642,  786,  930, 1074])

In [ ]:
#Introduction to statistical function

In [38]:
test_scores = np.array([32.33,56.77,99.55,34,22,55,66])

In [40]:
print("Mean test score of the students :")
print(np.mean(test_scores))

Mean test score of the students :
52.23571428571428


In [ ]:
#Find the Median

In [41]:
print(np.median(test_scores))

55.0


In [ ]:
#Statisctical function of Numpy:

In [42]:
import numpy as np

In [43]:
test_scores = np.array([32.32,56.98,21.52,44.32,55.55,70.50])

In [ ]:
#Mean of the test_scores...

In [44]:
print('mean of the test scores of the students')
print(np.mean(test_scores))

mean of the test scores of the students
46.865


In [45]:
test_scores = np.array([20,50,2,44,55,70])
print('mean of the test scores of the students')
print(np.mean(test_scores))

mean of the test scores of the students
40.166666666666664


In [ ]:
Dataset : Salary.csv --->CSV ...file format ...comma seperated value  #Comma delimited file ....
    It contain the salaries of a consulting company ,salary data information is there .....

In [65]:
salaries = np.genfromtxt('salary.csv',delimiter=',')

In [66]:
salaries #elipses...!

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [67]:
salaries.shape #1D-Array

(1147,)

In [ ]:
req: mean,median,standard deviation and variance

In [70]:
mean = np.mean(salaries)
median = np.median(salaries)
sd = np.std(salaries)
variance = np.var(salaries)

In [73]:
print('Mean = %i' %mean)
print('Median = %i' %median)
print('standard deviation = %i' %sd)
print('variance = %i' %variance)

Mean = 55894
Median = 48000
standard deviation = 55170
variance = 3043770333


In [ ]:
#Looping through Numpy:

In [52]:
a = np.arange(11)**2

a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [53]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [ ]:
#looping through Multi dimensional arrays:

$65000

In [87]:
Bank_customers =np.array([['arjun','ram','ganga','diwa','ramesh'],
                         [12,65,79,85,99],
                         [76,89,88,96,100]])

In [88]:
for i in Bank_customers:
    print('i= ',i) 

i=  ['arjun' 'ram' 'ganga' 'diwa' 'ramesh']
i=  ['12' '65' '79' '85' '99']
i=  ['76' '89' '88' '96' '100']


want to split entirely out of the for loop,how to achieve this...?

In [92]:
print(Bank_customers.flatten())

['arjun' 'ram' 'ganga' 'diwa' 'ramesh' '12' '65' '79' '85' '99' '76' '89'
 '88' '96' '100']


In [93]:
for element in Bank_customers.flatten():
    print(element) 

arjun
ram
ganga
diwa
ramesh
12
65
79
85
99
76
89
88
96
100
