In [ ]:
Introduction to Numpy:

In [ ]:
understanding Numpy:
    =>It is widely used to numerical computations and also scientific computation along with high end mathematical operations
    =>Data Analytics
    =>ML Algorithms
    =>DL Algorithms
    =>AI
    
Numpy will be base fundamental layer what exactly we will be using there...
Numpy deals with N-Dimentional arrays

IQ=>Array vs List differences

Arrays are much more optimized and much more efficient to use
Data access or retrival capacity will be enhanced..
    

In [ ]:
Installation of Numpy:

In [5]:
!pip install Numpy

In [6]:
!pip install Numpy --upgrade

Requirement already up-to-date: Numpy in c:\users\admin\anaconda3\lib\site-packages (1.18.3)


In [13]:
import numpy as np

In [14]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [15]:
type(array_one)

numpy.ndarray

In [17]:
numbers = [20,30,40,50,60] #list

In [18]:
array_two = np.array(numbers) #passing a list an array here..!
array_two

array([20, 30, 40, 50, 60])

In [19]:
type(array_two)

numpy.ndarray

In [20]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [ ]:
arrays =>Internally would be working on float datatype

In [21]:
arrays_of_zeros = np.zeros((3,4)) #3,4 matrix 3 as rows and 4 as columns
arrays_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
array_of_ones_int = np.ones((3,4), dtype=np.int16)

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [37]:
array_of_twos_int = np.ones((5,10), dtype=np.int16)

array_of_twos_int

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [38]:
array_of_twos_int = np.ones((10,20), dtype=np.int16)

array_of_twos_int

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
      dtype=int16)

In [41]:
x =('a','b','c','d','e','f') #Interview question

In [57]:
print(x[0:2])
print(x[2:4])
print(x[4:6])

('a', 'b')
('c', 'd')
('e', 'f')


In [54]:
print(x[0:2])

('a', 'b')


In [55]:
print(x[2:4])

('c', 'd')


In [56]:
print(x[4:6])

('e', 'f')


In [58]:
x = array([3, 6, 9, 12])
x/3.0
print(x)

NameError: name 'array' is not defined

In [69]:
array_three = np.array([1, 2, 3, 4])
array_three

array([1, 2, 3, 4])

In [75]:
array_y = np.array([3, 6, 9, 12])
array_y


array([ 3,  6,  9, 12])

In [61]:
food = {'pizza': 324, 'sandwich': 78, 'hot dog': 90}

In [76]:
food_list=list(data.values())
print(food_list)

NameError: name 'data' is not defined