In [ ]:
Understanding the concepts pf shallow copying and deep copying
View and copy

In [ ]:
Shallow Copying => view => we will be taking the base of the origional data

Deep Copying => copy the data but it's won't impact any base data if we did any updates.

In [ ]:
Introduction to shallow copying:

In [1]:
import numpy as np

In [4]:
fruits = np.array(['apple','orange','watermelon','papaya','kiwi'])

In [5]:
print(fruits)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [6]:
basket_1 = fruits.view()
basket_2 = fruits.view()

In [7]:
print(basket_1)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [8]:
print(basket_2)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [9]:
print(basket_1)
print(basket_2)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']
['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [11]:
print('ids for the arrays are different')
print('ids for fruits is : \n')
print(id(fruits))
print('ids for basket is : \n')
print(id(basket_1))
print(id(basket_2))      

ids for the arrays are different
ids for fruits is : 

101953168
ids for basket is : 

101963376
101963936


In [12]:
basket_1 is fruits

False

In [14]:
basket_1.base is fruits

True

In [15]:
print(fruits)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [16]:
print(basket_1)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [18]:
basket_1[1] ='mango'

In [19]:
print(basket_1)

['apple' 'mango' 'watermelon' 'papaya' 'kiwi']


In [20]:
print(fruits)

['apple' 'mango' 'watermelon' 'papaya' 'kiwi']


In [ ]:
Understanding the concept of deep copying:

In [ ]:
deep copying => copy

In [21]:
fruits = np.array(['apple','orange','watermelon','papaya','kiwi'])

In [22]:
basket = fruits.copy()

In [23]:
print(basket)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [24]:
basket is fruits

False

In [26]:
basket.base is fruits

False

In [27]:
print(fruits)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [28]:
print(basket)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [29]:
basket[4] = 'jock fruit'

In [30]:
print(basket)

['apple' 'orange' 'watermelon' 'papaya' 'jock fruit']


In [31]:
print(fruits)

['apple' 'orange' 'watermelon' 'papaya' 'kiwi']


In [ ]:
IQ:Whats the difference between shallow copying and Deep copying??
A copy is sometimes needed so one can change one copy without changing the other. In Python, 
there are two ways to create copies :
Deep copy
Shallow copy

"A shallow copy constructs a new compound object and then (to the extent possible) inserts references into it to the objects 
found in the original. A deep copy constructs a new compound object and then, recursively, 
inserts copies into it of the objects found in the original."
    

In [32]:
# import the important module in python 
import numpy as np 
         
# make matrix with numpy 
gfg = np.matrix('[1, 2, 3]') 
         
# applying matrix.copy() method 
geeks = gfg.copy() 

In [33]:
print(gfg)

[[1 2 3]]


In [34]:
print(geeks)

[[1 2 3]]


In [35]:
# import the important module in python 
import numpy as np 
         
# make a matrix with numpy 
gfg = np.matrix('[1, 2, 3; 4, 5, 6]') 
         
# applying matrix.copy() method 
geeks = gfg.copy() 
   
print(geeks) 

[[1 2 3]
 [4 5 6]]


In [38]:
# import the important module in python 
import numpy as np 
         
# make a matrix with numpy 
gfg = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9; 10, 11, 12]') 
         
# applying matrix.copy() method 
geeks = gfg.copy() 
   
print(geeks) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
# import the important module in python 
import numpy as np 
   
# make an array with numpy 
gfg = np.array([1, 2.5, 3, 4.8, 5]) 
   
# applying ndarray.__mul__() method 
print(gfg.__mul__(5)) 

[ 5.  12.5 15.  24.  25. ]


In [40]:
# import the important module in python 
import numpy as np 
   
# make an array with numpy 
gfg = np.array([[1, 2, 3, 4.45, 5], 
                [6, 5.5, 4, 3, 2.62]]) 
   
# applying ndarray.__mul__() method 
print(gfg.__mul__(5)) 

[[ 5.   10.   15.   22.25 25.  ]
 [30.   27.5  20.   15.   13.1 ]]
